# Run with:
# docker compose -f examples/simple_client/compose.yml up --build
services:
  runtime:
    image: simple_client
    depends_on:
      - policy_server
    build:
      context: ../..
      dockerfile: examples/simple_client/Dockerfile
    init: true
    tty: true
    network_mode: host
    environment:
      - CLIENT_ARGS

  policy_server:
    image: policy_server
    build:
      context: ../..
      dockerfile: scripts/docker/serve_policy.Dockerfile
    init: true
    tty: true
    network_mode: host
    volumes:
      - $PWD:/app
      - ${DATA_HOME:-~/.cache/robot_policy}:/model_assets
    environment:
      - SERVER_ARGS
      - DATA_HOME=/model_assets

    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
